version: "3.2"

services:
  api:
    container_name: agr.stage.intermine.solr.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_intermine_solr_env:latest
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "8983:8983"
    networks:
      - intermine
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  intermine:
